postgres:
  databases:
    - dropplets
  user: postgres
  password: dropplets1234
  host: localhost
  port: 5432
  minsize: 3
  maxsize: 20

redis:
  host: localhost
  port: 6379

host: 127.0.0.1
port: 9090
